# Generated by Django 2.2.5 on 2020-07-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Enter a your comment', max_length=300)),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Comment Date')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.blogs')),
            ],
            options={
                'ordering': ['comment_date'],
            },
        ),
    ]
